repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        args: [--write]
        files: '\.(md|json|yaml|yml)$'
  - repo: local
    hooks:
      - id: check-commit-msg
        name: "Valida mensagem de commit"
        language: system
        entry: |
          bash -c 'if ! grep -qE "^(feat|fix|doc|style|refactor|test|chore)[[:space:]]+\([a-zA-Z0-9-]+\):[[:space:]].+" "$1"; then echo -e "\nErro: A mensagem de commit não segue o padrão.\n\nFormato esperado: {tipo} ({chave_jira}): {descrição_curta}"; exit 1; fi'
        args: [".git/COMMIT_EDITMSG"]
        stages: [commit-msg]
